api_version = "2025-07"

[[extensions]]
name = "checkout-prazo-entrega"
handle = "checkout-prazo-entrega"
uid = "c4291ae9-d5bc-2051-ecef-1f6396f00eb783cc5d4c"
type = "ui_extension"

  [[extensions.targeting]]
  module = "./src/Checkout.jsx"
  target = "purchase.checkout.shipping-option-list.render-after"
