# fly.toml app configuration file generated for flow-bling-helper on 2025-06-26T17:14:44-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flow-bling-helper'
primary_region = 'gru'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'

[env]
  PORT = '3000'
  SCOPES = 'read_customers,read_orders,read_products,write_customers,write_orders,write_products'
  SHOPIFY_API_KEY = '51ae29758457cad8d47b5bf4caf80371'
  SHOPIFY_APP_URL = 'https://flow-bling-helper.fly.dev'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "ignore"
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
