# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "51ae29758457cad8d47b5bf4caf80371"
name = "flow-bling-helper"
handle = "flow-bling-helper-1"
application_url = "https://jeremy-exists-display-nj.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = ["orders/updated"]
  uri = "/webhooks/app/orders-updated"
  
[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,write_customers,read_customers, write_products, read_products"

[auth]
redirect_urls = ["https://jeremy-exists-display-nj.trycloudflare.com/auth/callback", "https://jeremy-exists-display-nj.trycloudflare.com/auth/shopify/callback", "https://jeremy-exists-display-nj.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
