# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "51ae29758457cad8d47b5bf4caf80371"
name = "flow-bling-helper"
handle = "flow-bling-helper-1"
application_url = "https://scanner-doctor-rosa-foundation.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "orders/updated" ]
  uri = "/webhooks/app/orders-updated"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_customers,write_orders,write_products"

[auth]
redirect_urls = ["https://scanner-doctor-rosa-foundation.trycloudflare.com/auth/callback", "https://scanner-doctor-rosa-foundation.trycloudflare.com/auth/shopify/callback", "https://scanner-doctor-rosa-foundation.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
