# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "51ae29758457cad8d47b5bf4caf80371"
name = "flow-bling-helper"
handle = "flow-bling-helper-1"
application_url = "https://flow-bling-helper.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "orders/updated" ]
  uri = "/webhooks/app/orders-updated"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locations,read_customers,read_orders,customer_read_orders,read_products,write_customers,write_orders,write_products,write_fulfillments,read_assigned_fulfillment_orders,write_merchant_managed_fulfillment_orders,write_third_party_fulfillment_orders,write_assigned_fulfillment_orders,read_merchant_managed_fulfillment_orders,read_third_party_fulfillment_orders,read_fulfillments,write_fulfillments"

[auth]
redirect_urls = [
  "https://flow-bling-helper.fly.dev/auth/callback",
  "https://flow-bling-helper.fly.dev/auth/shopify/callback",
  "https://flow-bling-helper.fly.dev/api/auth/callback"
]

[pos]
embedded = false

[capabilities]
network_access = true

[[extensions]]
name = "Order Metafield Tracking Code"
handle = "order-metafield-tracking-code"
type = "ui_extension"

  [[extensions.targeting]]
  module = "./src/BlockExtension.jsx"
  target = "admin.order-details.block.render"

  [[extensions.targeting]]
  module = "./src/Checkout.jsx"
  target = "customer-account.order-status.block.render"

  [[extensions.metafields]]
  namespace = "tracking"
  key = "link_nota_fiscal_bling"
  name = "Nota Fiscal Customer Account"
  handle = "nota-fiscal-customer-account"
  type = "ui_extension"
  network_access = true

  [[extensions.metafields]]
  namespace = "tracking"
  key = "link_nota_fiscal_bling"
