[[extensions]]
name = "Order Metafield Tracking Code"
handle = "order-metafield-tracking-code"

uid = "3a318c09-acaf-254c-d870-817d7faa93d88ab6e1a6"

type = "ui_extension"
api_version = "2025-07"


  [[extensions.targeting]]
  target = "admin.order-details.block.render"
  module = "./src/BlockExtension.jsx"
